name: CUDA CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  linux_build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install CUDA and nvcc
      run: |
        sudo apt update
        sudo apt install nvidia-cuda-toolkit -y
        sudo apt install libcunit1 libcunit1-dev -y
    - name: make
      run: make all
    - name: build tests
      run: make test
    - name: run tests
      run: ./bin/test.out --cpu